spring:
  application:
    name: kopring

  datasource:
    url: jdbc:postgresql://localhost:5432/kopring
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  data:
    jpa:
      auditing:
        enabled: true
